//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viten.QueryBuilder.Culture {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viten.QueryBuilder.Culture.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверные параметры Page.
        /// </summary>
        internal static string Err_InvalidPage {
            get {
                return ResourceManager.GetString("Err_InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указание OrderBy для постраничного запроса.
        /// </summary>
        internal static string Err_OrderByNeedForPage {
            get {
                return ResourceManager.GetString("Err_OrderByNeedForPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов Distinct.
        /// </summary>
        internal static string Err_RepeatDistinct {
            get {
                return ResourceManager.GetString("Err_RepeatDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов From.
        /// </summary>
        internal static string Err_RepeatFrom {
            get {
                return ResourceManager.GetString("Err_RepeatFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов Having.
        /// </summary>
        internal static string Err_RepeatHaving {
            get {
                return ResourceManager.GetString("Err_RepeatHaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов Page.
        /// </summary>
        internal static string Err_RepeatPage {
            get {
                return ResourceManager.GetString("Err_RepeatPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов Top.
        /// </summary>
        internal static string Err_RepeatTop {
            get {
                return ResourceManager.GetString("Err_RepeatTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов Values.
        /// </summary>
        internal static string Err_RepeatValues {
            get {
                return ResourceManager.GetString("Err_RepeatValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный вызов Where.
        /// </summary>
        internal static string Err_RepeatWhere {
            get {
                return ResourceManager.GetString("Err_RepeatWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый тип Oper.SubQuery.
        /// </summary>
        internal static string Err_SubQueryUnavelable {
            get {
                return ResourceManager.GetString("Err_SubQueryUnavelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя использовать Top совместно с Page.
        /// </summary>
        internal static string Err_TopWithPage {
            get {
                return ResourceManager.GetString("Err_TopWithPage", resourceCulture);
            }
        }
    }
}
