//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viten.QueryBuilder.Test {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viten.QueryBuilder.Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;Columns&quot;:[{&quot;Expression&quot;:{&quot;CaseClause&quot;:{&quot;Terms&quot;:[]},&quot;ValueCode&quot;:0,&quot;StringValue&quot;:&quot;a&quot;,&quot;Type&quot;:1}},{&quot;Expression&quot;:{&quot;CaseClause&quot;:{&quot;Terms&quot;:[]},&quot;ValueCode&quot;:0,&quot;StringValue&quot;:&quot;b&quot;,&quot;Type&quot;:1}}],&quot;WherePhrase&quot;:{&quot;Relationship&quot;:0,&quot;Terms&quot;:[],&quot;SubClauses&quot;:[{&quot;Relationship&quot;:0,&quot;Terms&quot;:[{&quot;Values&quot;:[],&quot;Expr1&quot;:{&quot;CaseClause&quot;:{&quot;Terms&quot;:[]},&quot;ValueCode&quot;:0,&quot;StringValue&quot;:&quot;id&quot;,&quot;Type&quot;:1},&quot;Expr2&quot;:{&quot;CaseClause&quot;:{&quot;Terms&quot;:[]},&quot;ConstantValue&quot;:{&quot;NumericValue&quot;:0,&quot;Type&quot;:1},&quot;ValueCode&quot;:1,&quot;Type&quot;:2},&quot;Op&quot;:0,&quot;Type&quot;:0}],&quot;SubClauses&quot;:[]}]},&quot;HavingPhrase&quot;:{ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string test_cmd {
            get {
                return ResourceManager.GetString("test_cmd", resourceCulture);
            }
        }
    }
}
